language: node_js

node_js:
  - '8'
  - '10'
  - '12'

before_install:
  - mkdir /tmp/bin
  - "wget -nv https://raw.githubusercontent.com/fumiyas/home-commands/master/echo-sd -O /tmp/bin/echo-sd"
  - "chmod +x /tmp/bin/echo-sd"
  - export PATH=$PATH:/tmp/bin/

cache: npm

script:
  - npm test
