language: node_js

node_js:
  - '8'
  - '10'
  - '12'

before_install:
  - "wget -nv https://raw.githubusercontent.com/fumiyas/home-commands/master/echo-sd -O /usr/local/bin/echo-sd"
  - "chmod +x /usr/local/bin/echo-sd"

cache: npm

script:
  - npm test
