language: node_js

node_js:
  - '8'
  - '10'
  - '12'

cache: npm

before_script:
  - wget -nv https://raw.githubusercontent.com/fumiyas/home-commands/master/echo-sd -O /usr/local/bin/echo-sd

script:
  - npm test
